// <auto-generated />
namespace AnimalKingdom.Module.Feline.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class FelineSetup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FelineSetup));
        
        string IMigrationMetadata.Id
        {
            get { return "201301091454064_FelineSetup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
